exp_detail : '' 

# Train
num_epochs : 200
usegpu: true
gpuID: 0

# model save path
model_save_dir : '../saved_model'
best_model_path : '../saved_model/4-29-13-46/epoch_0.pt'

# dataset
raw_data_path : './graph2seq.pkl'
data_path : './data.pkl'

train_pkl : '../../Datasets/wikifonia/train'
val_pkl : '../../Datasets/wikifonia/val'
test_pkl : '../../Datasets/wikifonia/test'
rpp_feat2idx_path : '../../DataProcess/feat2idx_rpp.pkl'

tick_resolution : 120
rpp_seq_max : 256
token_seq_max : 1024
bar_max : 32
batch_size: 16

d_embed: 128
d_model: 512

# edge_type : 8
# edge_dim : 128
# edge_detail_dim : 3
num_workers: 0
dropout: 0.25
n_head : 8
num_layers : 8

# optimizer
lr : 0.00005
grad_clip : 1.0




# scheduled sampling


# adjacency-aware positional encoding for RPP encoder


note_feature_loss_weights:
  bar: 1.0
  position: 1.0
  duration: 1.0
  pitch: 1.0
  velocity: 1.0



# Bar=idx | Position=(idx-1)*30 | Duration=(idx-1)*30 | NoteCnt=idx | RhythmType=(idx-1) | MelodyOutline=(idx-1)
#rpp_feature_selected : ['Bar','Position','Duration','NoteCnt','RhythmType','MelodyOutline']
#rpp_feature_dim_dict: {'Bar':65, # <pad> [1-64]
#                       'Position':65, # <pad> [1-64]
#                       'Duration':129, # <pad> [1-128]
#                       'NoteCnt':4, # <pad> [1-3]
#                       'RhythmType':8, # <pad> [1-7]
#                       'MelodyOutline':15} # <pad> [1-14]
rpp_feature_all : ['bar','position','duration','rhythm_pattern','melody_contour','pitch_region']
# rpp_feature_selected : ['bar','position','duration','rhythm_pattern','melody_contour','pitch_region']
# Removed pitch_region to reduce error propagation from stage 2 and rely on decoder autoregression
rpp_feature_selected : ['bar','position','duration','rhythm_pattern','melody_contour']
rpp_feature_dim_dict: {"bar": 130,
                      "position": 18,
                      "duration": 35,
                      "rhythm_pattern": 9,
                      "melody_contour": 15,
                      "pitch_region": 130} 

                       

# Bar=idx-1 | Position=(idx-1) | Duration=idx-1   | Pitch=idx-1     |  Velocity=idx-1
# [0,1,2]   | [0,1,2]          | [0,1,2,3]        | [0,1,2,3]       |  [0,1,2,3]
note_feature_selected : ['bar','position','duration','pitch']
note_feature_dim_dict: {'bar':129,     # <pad> + [1-129]
                        'position':17, # <pad> + [1-16]
                        'duration':18, # <pad> + [1-17]
                        'pitch': 129, # <pad> + [1-128]
                      } 


# inference
input_lenth : 0
inference_lenth : 256
temperature:
  - 1.0  # bar
  - 1.0  # position
  - 1.2  # duration
  - 1.3  # pitch
  - 1.0  # velocity
sampling_topk: 5
deterministic_inference: false
# midi_dict = {'name':'','rpp_feature_seq':[],'rpp_edge_seq':[],'rpp_mask':[],'note_seq':[],'note_mask':[]}